# Generated by Django 5.1.1 on 2024-09-23 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=100)),
                ('control', models.CharField(choices=[('відсутній', 'Відсутній'), ('залік', 'Залік'), ('іспит', 'Іспит')], max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='subject_images/')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.lessontype')),
            ],
        ),
    ]
