# Generated by Django 5.1.1 on 2024-09-24 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='control',
            field=models.CharField(choices=[('Відсутній', 'Відсутній'), ('Залік', 'Залік'), ('Іспит', 'Іспит')], max_length=50),
        ),
    ]
