# Generated by Django 5.1.1 on 2024-09-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_author_alter_subject_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='control',
            field=models.CharField(choices=[('Відсутній', 'Відсутній'), ('Залік', 'Залік'), ('Іспит', 'Іспит')], max_length=50, verbose_name='Контроль'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subject_images/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.lessontype', verbose_name='Тип заняття'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва предмету'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='Спеціальність'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.CharField(max_length=100, verbose_name='Викладач'),
        ),
    ]
