# Generated by Django 5.1 on 2024-08-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag'},
        ),
    ]